### PR TITLE
Fix two small typos in README.mkdn

### PR DESCRIPTION
**Pull request by Devices**
`data` should be `date` and "filed" should be "field".

### CODE REVIEW

**Comment by xatasan** [comment]
I just managed to push a commit updating the README file, so there are a few conflicts now. Would you mind updating your pull request, since the structure and the line length was changed, making the conflicts rather hard to resolve.

**Comment by Devices** [comment]
Never resolved conflicts before, but I think I did it correctly.

What does being part of the group account mean? That I have the same privileges as you and schalken?

**Comment by xatasan** [comment]
As far as I see it, it's all ok - will merge.

>What does being part of the group account mean? That I have the same privileges as you and schalken?

If you plan on contributing to the _texts_ repo (and maybe the _mirror tools_ too), it would make it easier for you since you'd have write access, next to read access. And a few other things, I guess, but these write access would be the most significant permission.

**Comment by Devices** [comment]
Sounds good to me. I may still do a pull request for my first text, but we'll see since we will probably discuss it over email anyway.

**Pull request merged**
